package com.example.kotlinbasic

//CON Ctrl + i DENTRO DE LA CLASE OBJ AUTOMATICAMENTE CARGA interface

//ES UNA CLASE INTERMEDIARIA QUE PUEDE MODIFICAR LA FORMA EN QUE VEMOS UNA CLASE
//SOLO LO QUE SE DEFINE EN LA INTERFAZ ES LO QUE SE PUEDE VER DENTRO DE OTRA CLASE QUE LLAMEN A
//ESA CLASE PERO COMO INSTANCIA DE LA INTERFAZ
interface Boss {
    fun namePerson(): String
    fun netSalary(): Float
}